"use client";

import React, { useState, useEffect, useRef } from "react";
import Link from "next/link";
import { 
  ShieldCheck, 
  Search, 
  FileText, 
  ChevronRight,
  Download,
  AlertCircle,
  ExternalLink,
  ChevronDown,
  ChevronUp,
  Mail,
  Scale,
  Printer,
  BookOpen
} from "lucide-react";

interface Section {
  id: string;
  title: string;
  badge?: string;
  paragraphs: string[];
  bulletPoints?: string[];
  tableData?: { term: string; definition: string }[];
}

const termsSections: Section[] = [
  {
    id: "acceptance-of-terms",
    title: "Section 1 — Acceptance of Terms",
    paragraphs: [
      "By accessing, querying, integrating, or utilizing the DeepSense Platform, including our fraud intelligence systems, AI-powered operational tooling, real-time API integrations, graph intelligence modeling, transaction monitoring algorithms, enterprise governance infrastructure, and automated reporting systems, you agree to comply with and be bound by these Terms of Service and all applicable global laws and regulatory frameworks.",
      "If you are accessing or configuring the Platform on behalf of a financial institution, corporation, or other legal entity (\"Organization\"), you represent and warrant that you possess the explicit legal authority to bind that Organization and its affiliates to these terms. If you do not possess such authority, or if you do not agree to these terms, you must immediately terminate all API queries and platform integrations."
    ]
  },
  {
    id: "definitions",
    title: "Section 2 — Definitions",
    paragraphs: [
      "For the purposes of this Agreement, the following terms shall have the designated meanings. These definitions apply to all operational documents, performance audits, and SLA measurements:"
    ],
    tableData: [
      { term: "Platform", definition: "The DeepSense software-as-a-service application, neural networks, device fingerprinting scripts, and global fraud prevention infrastructure." },
      { term: "Customer Data", definition: "All transaction telemetry, identity documents, IP metadata, and organizational logs uploaded or queried via DeepSense." },
      { term: "AI Outputs", definition: "Automated scores, anomaly alerts, graph relationships maps, and explainable intelligence reports generated by our neural engines." },
      { term: "Organization", definition: "The enterprise customer entity that has entered into an active service agreement with DeepSense." },
      { term: "User", definition: "An authorized employee, investigator, administrator, or compliance officer of the Organization." },
      { term: "Services", definition: "All API integrations, scoring engines, case portals, webhook pipelines, and analytics tooling provided under this Agreement." }
    ]
  },
  {
    id: "account-responsibilities",
    title: "Section 3 — Account Responsibilities",
    paragraphs: [
      "Organizations are responsible for managing internal system access and maintaining tight security credentials across all integration points. Specifically, Organizations are required to:",
      "Users are also bound by strict operating protocols to preserve platform integrity:"
    ],
    bulletPoints: [
      "Organization: Actively manage and audit user access levels via the central Admin Console.",
      "Organization: Enforce enterprise Multi-Factor Authentication (MFA) across all administrative accounts.",
      "Organization: Prevent unauthorized credential reuse or credential sharing across compliance departments.",
      "Organization: Maintain accurate administrative contact records for critical security alerts.",
      "User: Maintain absolute confidentiality of all active login tokens and dashboard credentials.",
      "User: Use verified MFA methods when logging in from new networks or devices.",
      "User: Immediately report any potential security credential compromises to security@deepsense.ai."
    ]
  },
  {
    id: "permitted-usage",
    title: "Section 4 — Permitted Usage",
    paragraphs: [
      "The Platform is licensed to the Organization solely for legitimate security, AML compliance, and fraud detection operations. Permitted activities are restricted to:"
    ],
    bulletPoints: [
      "Conducting automated real-time fraud detection and risk scoring on payment flows.",
      "Executing Anti-Money Laundering (AML) monitoring and PEP/sanctions screening.",
      "Managing forensic fraud investigations and compiling STR records.",
      "Orchestrating event-driven compliance workflows and rules-based decisions.",
      "Validating customer identity credentials and performing liveness check comparisons.",
      "Analyzing active device telemetry to intercept account takeover (ATO) campaigns.",
      "Generating aggregated risk performance analytics for executive or board reporting."
    ]
  },
  {
    id: "restricted-usage",
    title: "Section 5 — Restricted Activities",
    paragraphs: [
      "To preserve platform security, the license granted to the Organization is subject to absolute compliance limitations. Users, developers, and administrators are strictly prohibited from:"
    ],
    bulletPoints: [
      "Using the Platform in violation of global anti-corruption, sanctions, or local data protection regulations.",
      "Conducting unauthorized mass surveillance or profiling outside approved anti-fraud parameters.",
      "Scraping, caching, or mining data from DeepSense API nodes to train competing AI models.",
      "Attempting to reverse-engineer, decompile, or extract the parameters of DeepSense neural nets.",
      "Introducing viruses, trojan horses, worms, or other malicious payloads into our API tunnels.",
      "Abusing API quotas, triggering artificial traffic surges, or bypassing active rate-limit thresholds.",
      "Interfering with platform infrastructure, hardware hosts, or secondary databases.",
      "Conducting active penetration testing or vulnerability scanning without prior explicit authorization."
    ]
  },
  {
    id: "ai-operational-intelligence",
    title: "Section 6 — AI & Operational Intelligence",
    paragraphs: [
      "DeepSense AI models generate probabilistic fraud indicators, anomaly maps, and decision support recommendations to accelerate operational investigations. Organizations acknowledge that:",
      "Therefore, the Organization retains absolute responsibility for all operational actions, including transaction reversals, customer account suspensions, regulatory reporting accuracy, and active compliance policy settings."
    ],
    bulletPoints: [
      "AI outputs represent risk suggestions based on incoming telemetry and historical patterns.",
      "Models generate scores and explainability factors that do not replace human investigator oversight.",
      "Automated scores are probabilistic and require regular verification against case parameters."
    ]
  },
  {
    id: "data-ownership",
    title: "Section 7 — Data Ownership",
    paragraphs: [
      "The Organization retains exclusive title, ownership, copyright, and trade secret claims to all Customer Data submitted to DeepSense.",
      "DeepSense processes Customer Data solely to deliver the agreed fraud prevention services, improve real-time anomaly detection, monitor API health, and generate aggregated, completely anonymized risk benchmarks. We guarantee that DeepSense does not sell, rent, or share personal transaction telemetry with third-party advertisers."
    ]
  },
  {
    id: "security",
    title: "Section 8 — Security Commitments",
    paragraphs: [
      "DeepSense implements and maintains a rigorous information security framework based on standard Zero-Trust principles. Our primary security controls include:",
      "We undergo regular bi-annual SOC 2 Type II and ISO 27001 audit examinations conducted by independent certified CPA firms."
    ],
    bulletPoints: [
      "End-to-end data encryption using TLS 1.3 in transit and AES-256 at rest.",
      "Strict role-based access control (RBAC) separating administrative and investigator credentials.",
      "Total multi-tenant database isolation to prevent cross-customer data leakage.",
      "Continuous system logging, performance monitoring, and compliance logging.",
      "Regular penetration tests, container security scanning, and vulnerability patching.",
      "Incident response plans designed to detect and quarantine potential security alerts within 15 minutes."
    ]
  },
  {
    id: "compliance",
    title: "Section 9 — Compliance",
    paragraphs: [
      "DeepSense operates as a Data Processor under European GDPR, UK GDPR, and other regional data protection acts. The Customer warrants that it has secured all necessary legal consents, privacy policy disclosures, and statutory authorizations to collect, transmit, and process transactional and biometric telemetry using the Platform.",
      "Organizations are responsible for ensuring their compliance workflows conform with local regulatory requirements, Central Bank guidelines, and consumer privacy rights."
    ]
  },
  {
    id: "billing",
    title: "Section 10 — Billing & Subscription Terms",
    paragraphs: [
      "Enterprise access is provided on a subscription basis governed by a signed Order Form. Pricing models are based on committed API volumes, platform feature tiers, and investigator user seat counts.",
      "All invoices are payable within 30 days of receipt. In the event of unpaid balances exceeding 45 days, DeepSense reserves the right to suspend API access, restrict case portals, or terminate the active tenancy after providing 5 business days' written notice."
    ]
  },
  {
    id: "service-availability",
    title: "Section 11 — Service Availability",
    paragraphs: [
      "DeepSense targets a 99.99% monthly availability SLA for all production API nodes. Uptime and response speed parameters are governed by our master Service Level Agreement.",
      "Standard system maintenance is conducted during low-traffic windows announced at least 5 business days in advance via our central developer console."
    ]
  },
  {
    id: "intellectual-property",
    title: "Section 12 — Intellectual Property",
    paragraphs: [
      "DeepSense retains exclusive title, copyright, patent claims, and intellectual property rights to all platform software, neural models, case dashboards, device intelligence scripts, and reporting templates.",
      "No rights, licenses, or intellectual properties are transferred under this Agreement except the limited, revocable right to query our API portals to secure Customer transactions."
    ]
  },
  {
    id: "confidentiality",
    title: "Section 13 — Confidentiality",
    paragraphs: [
      "Both parties agree to protect and maintain the strict confidentiality of all non-public technical, operational, financial, and strategic information shared during the service engagement. Confidential information includes proprietary fraud parameters, neural network structures, API logs, and data security audits."
    ]
  },
  {
    id: "liability",
    title: "Section 14 — Liability Limitations",
    paragraphs: [
      "To the maximum extent permitted by applicable law, DeepSense shall not be liable for indirect, incidental, special, punitive, or consequential damages, including loss of profit, operational losses, system downtime, third-party hosting interruptions, or decisions made based on AI-generated anomaly scores.",
      "In no event shall DeepSense's total aggregate liability for all claims under this Agreement exceed the total fees paid by the Organization during the twelve (12) months preceding the event giving rise to the claim."
    ]
  },
  {
    id: "termination",
    title: "Section 15 — Termination",
    paragraphs: [
      "Either party may terminate this Agreement if the other party commits a material breach and fails to remedy it within 30 days of written notice. DeepSense reserves the right to immediately suspend platform access if we detect an active security threat, API abuse, or suspected illegal activity originating from Customer infrastructure.",
      "Upon termination, Customer data will be retained for up to 30 days to facilitate secure migration, after which it will be permanently purged using cryptographically secure deletion standards."
    ]
  },
  {
    id: "governing-law",
    title: "Section 16 — Governing Law",
    paragraphs: [
      "These Terms of Service and any associated order contracts shall be governed by, construed, and enforced in accordance with the jurisdiction specified in the Master Services Agreement (MSA) signed between the Organization and DeepSense, without regard to conflict of laws principles."
    ]
  },
  {
    id: "contact-information",
    title: "Section 17 — Contact Information",
    paragraphs: [
      "For all formal communication, regulatory reports, security alerts, and compliance requests, please route inquiries to the designated team:"
    ],
    bulletPoints: [
      "Legal Inquiries: legal@deepsense.ai",
      "Data Privacy & DPO: privacy@deepsense.ai",
      "Security Audits: security@deepsense.ai",
      "Regulatory Compliance: compliance@deepsense.ai"
    ]
  }
];

export default function TermsOfServicePage() {
  const [searchQuery, setSearchQuery] = useState("");
  const [expandedSections, setExpandedSections] = useState<Record<string, boolean>>(() => {
    const initial: Record<string, boolean> = {};
    termsSections.forEach(s => {
      initial[s.id] = true; // All open by default
    });
    return initial;
  });

  const sectionRefs = useRef<Record<string, HTMLDivElement | null>>({});

  const toggleSection = (id: string) => {
    setExpandedSections(prev => ({
      ...prev,
      [id]: !prev[id]
    }));
  };

  const expandAll = () => {
    const updated: Record<string, boolean> = {};
    termsSections.forEach(s => {
      updated[s.id] = true;
    });
    setExpandedSections(updated);
  };

  const collapseAll = () => {
    const updated: Record<string, boolean> = {};
    termsSections.forEach(s => {
      updated[s.id] = false;
    });
    setExpandedSections(updated);
  };

  const scrollToAnchor = (id: string) => {
    const el = sectionRefs.current[id];
    if (el) {
      // Ensure section is expanded before scrolling
      setExpandedSections(prev => ({ ...prev, [id]: true }));
      el.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  };

  // Filter sections based on search query
  const filteredSections = termsSections.filter(section => {
    const query = searchQuery.toLowerCase();
    const titleMatch = section.title.toLowerCase().includes(query);
    const paraMatch = section.paragraphs.some(p => p.toLowerCase().includes(query));
    const bulletMatch = section.bulletPoints?.some(b => b.toLowerCase().includes(query));
    const tableMatch = section.tableData?.some(t => t.term.toLowerCase().includes(query) || t.definition.toLowerCase().includes(query));

    return titleMatch || paraMatch || bulletMatch || tableMatch;
  });

  return (
    <div className="min-h-screen bg-zinc-50 text-neutral-900 font-manrope">
      
      {/* 1. Hero Header */}
      <section className="bg-neutral-900 text-white py-16 px-6 md:px-12 lg:px-24 border-b border-white/5 relative overflow-hidden">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[300px] bg-brand-lime/10 blur-[130px] rounded-full pointer-events-none" />
        
        <div className="max-w-[1440px] mx-auto relative z-10 space-y-6">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-white/5 rounded-full text-brand-lime text-[10px] font-extrabold uppercase tracking-widest border border-white/10">
            <Scale className="w-3.5 h-3.5" />
            LEGAL AGREEMENT
          </div>
          
          <h1 className="text-4xl md:text-6xl font-black tracking-tight uppercase italic leading-[1.0] text-white">
            Terms of <span className="text-zinc-400">Service.</span>
          </h1>
          
          <p className="text-zinc-400 text-base md:text-lg font-inter max-w-[800px] leading-relaxed italic">
            These Terms of Service govern access to and use of the DeepSense platform, fraud intelligence infrastructure, APIs, AI systems, operational analytics, and enterprise services.
          </p>

          {/* Metadata Horizontal Bar */}
          <div className="pt-6 border-t border-white/10 grid grid-cols-2 md:grid-cols-4 gap-6 max-w-4xl">
            <div className="space-y-1">
              <span className="text-[10px] uppercase font-bold text-zinc-500 tracking-wider font-mono">Effective Date</span>
              <p className="text-xs font-bold text-white">January 1, 2026</p>
            </div>
            <div className="space-y-1">
              <span className="text-[10px] uppercase font-bold text-zinc-500 tracking-wider font-mono">Last Updated</span>
              <p className="text-xs font-bold text-white">January 1, 2026</p>
            </div>
            <div className="space-y-1">
              <span className="text-[10px] uppercase font-bold text-zinc-500 tracking-wider font-mono">Version</span>
              <p className="text-xs font-bold text-brand-lime">v2.0 Enterprise</p>
            </div>
            <div className="space-y-1">
              <span className="text-[10px] uppercase font-bold text-zinc-500 tracking-wider font-mono">Format</span>
              <button 
                onClick={() => window.print()}
                className="text-xs font-bold text-white hover:underline flex items-center gap-1 text-left"
              >
                <Download className="w-3 h-3 text-brand-lime" />
                PDF Download
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* 2. Interactive Navigation Panel & Workspace */}
      <section className="max-w-[1440px] mx-auto px-6 md:px-12 lg:px-24 py-12">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start">
          
          {/* Left Column Sticky Sidebar Navigator */}
          <div className="lg:col-span-4 bg-white border border-zinc-200 rounded-[32px] p-6 shadow-sm sticky top-28 space-y-6">
            <div className="space-y-2">
              <h3 className="text-base font-bold text-neutral-900">Document Framework</h3>
              <p className="text-[11px] text-zinc-500 font-inter">Navigate specific legal sections and responsibilities.</p>
            </div>

            {/* Quick Action Toggle All */}
            <div className="flex gap-2">
              <button 
                onClick={expandAll}
                className="flex-1 py-1.5 bg-zinc-100 hover:bg-zinc-200 rounded-lg text-[10px] font-bold text-neutral-800 transition-all"
              >
                Expand All
              </button>
              <button 
                onClick={collapseAll}
                className="flex-1 py-1.5 bg-zinc-100 hover:bg-zinc-200 rounded-lg text-[10px] font-bold text-neutral-800 transition-all"
              >
                Collapse All
              </button>
            </div>

            {/* Policy Clause Search */}
            <div className="relative">
              <Search className="w-4 h-4 text-zinc-400 absolute left-4 top-1/2 -translate-y-1/2" />
              <input 
                type="text" 
                placeholder="Search contract clauses..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-11 pr-4 py-3 bg-zinc-50 border border-zinc-200 rounded-full text-xs font-bold text-neutral-900 focus:outline-none focus:border-neutral-900 transition-all"
              />
            </div>

            {/* Anchored Sidebar Links */}
            <div className="space-y-1.5 max-h-[380px] overflow-y-auto pr-1 scrollbar-thin">
              {termsSections.map((section, idx) => (
                <button 
                  key={idx}
                  onClick={() => scrollToAnchor(section.id)}
                  className="w-full flex items-center justify-between p-3 rounded-xl border border-zinc-100 hover:border-zinc-200 hover:bg-zinc-50 text-left transition-all"
                >
                  <span className="text-xs font-extrabold text-neutral-900">{section.title.split(" — ")[1] || section.title}</span>
                  <ChevronRight className="w-3.5 h-3.5 text-zinc-400" />
                </button>
              ))}
            </div>

            {/* External Links */}
            <div className="pt-4 border-t border-zinc-100 flex items-center justify-between text-[11px]">
              <span className="text-zinc-400 font-inter">Custom MSA terms?</span>
              <Link href="/company/contact" className="text-neutral-900 font-bold hover:underline flex items-center gap-1">
                Contact Sales
                <ExternalLink className="w-3 h-3" />
              </Link>
            </div>
          </div>

          {/* Right Column Actual Document Content */}
          <div className="lg:col-span-8 bg-white border border-zinc-200 rounded-[32px] p-8 md:p-14 shadow-sm space-y-10">
            
            {filteredSections.map((section) => {
              const isExpanded = expandedSections[section.id];
              return (
                <div 
                  key={section.id}
                  ref={(el) => { sectionRefs.current[section.id] = el; }}
                  className="border-b border-zinc-100 pb-8 last:border-b-0 last:pb-0 scroll-mt-28"
                >
                  {/* Collapsible Header */}
                  <button 
                    onClick={() => toggleSection(section.id)}
                    className="w-full flex items-center justify-between py-4 text-left group"
                  >
                    <h2 className="text-lg md:text-xl font-bold font-manrope text-neutral-900 group-hover:text-zinc-600 transition-colors uppercase tracking-tight italic">
                      {section.title}
                    </h2>
                    {isExpanded ? (
                      <ChevronUp className="w-5 h-5 text-zinc-400 group-hover:text-neutral-900" />
                    ) : (
                      <ChevronDown className="w-5 h-5 text-zinc-400 group-hover:text-neutral-900" />
                    )}
                  </button>

                  {/* Stateful Expanded Section Body */}
                  {isExpanded && (
                    <div className="mt-4 space-y-5 font-inter text-sm text-zinc-600 leading-relaxed italic animate-fadeIn">
                      {section.paragraphs.map((p, pIdx) => (
                        <p key={pIdx}>{p}</p>
                      ))}

                      {/* Display Bullet Points if applicable */}
                      {section.bulletPoints && (
                        <ul className="space-y-3.5 pl-6 list-disc text-zinc-600">
                          {section.bulletPoints.map((bullet, bIdx) => (
                            <li key={bIdx} className="pl-1">
                              {bullet.includes(": ") ? (
                                <>
                                  <strong className="text-neutral-900 not-italic uppercase tracking-tight text-xs">{bullet.split(": ")[0]}:</strong>
                                  <span>{bullet.split(": ")[1]}</span>
                                </>
                              ) : (
                                <span>{bullet}</span>
                              )}
                            </li>
                          ))}
                        </ul>
                      )}

                      {/* Display Definitions Table if applicable */}
                      {section.tableData && (
                        <div className="overflow-x-auto border border-zinc-200 rounded-2xl mt-6">
                          <table className="w-full text-left border-collapse text-xs">
                            <thead>
                              <tr className="bg-zinc-50 border-b border-zinc-200">
                                <th className="p-4 font-bold text-neutral-900 uppercase tracking-tight">Term</th>
                                <th className="p-4 font-bold text-neutral-900 uppercase tracking-tight">Definition</th>
                              </tr>
                            </thead>
                            <tbody>
                              {section.tableData.map((row, rIdx) => (
                                <tr key={rIdx} className="border-b border-zinc-100 last:border-b-0 hover:bg-zinc-50/50 transition-colors">
                                  <td className="p-4 font-extrabold text-neutral-900 font-mono text-[11px] whitespace-nowrap">{row.term}</td>
                                  <td className="p-4 text-zinc-500 font-inter italic">{row.definition}</td>
                                </tr>
                              ))}
                            </tbody>
                          </table>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              );
            })}

            {filteredSections.length === 0 && (
              <div className="text-center py-20 space-y-4">
                <AlertCircle className="w-10 h-10 text-zinc-300 mx-auto" />
                <h3 className="text-base font-bold text-neutral-900">No Clauses Found</h3>
                <p className="text-xs text-zinc-500 font-inter max-w-md mx-auto leading-relaxed">
                  No sections match your query &ldquo;{searchQuery}&rdquo;. Try using terms like &ldquo;compliance&rdquo;, &ldquo;data&rdquo;, or &ldquo;SLA&rdquo;.
                </p>
              </div>
            )}
          </div>
        </div>
      </section>

      {/* 3. Questions Bottom CTA Block */}
      <section className="max-w-[1440px] mx-auto px-6 md:px-12 lg:px-24 pb-24">
        <div className="bg-neutral-900 text-white rounded-[32px] p-8 md:p-16 relative overflow-hidden border border-white/5 shadow-2xl flex flex-col md:flex-row justify-between items-center gap-8">
          <div className="absolute top-0 right-0 w-[450px] h-[450px] bg-brand-lime/10 blur-[130px] rounded-full pointer-events-none" />
          
          <div className="space-y-3 text-left relative z-10 max-w-2xl">
            <h2 className="text-3xl md:text-5xl font-black italic uppercase leading-none tracking-tight">
              Questions About <span className="text-zinc-400">These Terms?</span>
            </h2>
            <p className="text-zinc-400 text-sm font-inter leading-relaxed max-w-lg italic">
              Our specialized legal and operational compliance offices are available 24/7 to review custom service contracts, MSA amendments, and regional governance policies.
            </p>
          </div>

          <div className="flex flex-col sm:flex-row gap-4 relative z-10 w-full sm:w-auto">
            <Link 
              href="mailto:legal@deepsense.ai"
              className="px-8 py-4 bg-brand-lime hover:bg-brand-lime-hover text-neutral-900 rounded-full font-bold text-xs transition-all text-center uppercase tracking-wider"
            >
              Contact Legal
            </Link>
            <button 
              onClick={() => window.print()}
              className="px-8 py-4 bg-white/5 hover:bg-white/10 border border-white/10 rounded-full font-bold text-xs transition-all text-center flex items-center justify-center gap-2 text-white uppercase tracking-wider"
            >
              <Printer className="w-3.5 h-3.5 text-brand-lime" />
              Download PDF
            </button>
          </div>
        </div>
      </section>

    </div>
  );
}
